
python:

  - "2.7"

install:
  - pip install requests

before_script:
  - chmod +x travis_build.py

script:
  - ./travis_build.py

    ## 将生成的文件push到别的仓库
    #deploy:
    #  provider: pages
    #  local-dir: a              # 提交那个目录
    #  repo: xianxiaoyin/xxy    # 提交到那个仓库
    #  skip-cleanup: true        # 是否保存构建文件
    #  github-token: $GITHUB_TOKEN   # 提交到所在仓库的token
    #  target-branch: master         # 提交到那个分支
    #  keep-history: true            # 是否覆盖提交
    #
#before_deploy:
#    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d-%H-%M')}
#    - git tag $TRAVIS_TAG
#deploy:
#  provider: releases
#  repo: xianxiaoyin/xxy
#  api_key:
#    secure: $GITHUB_TOKEN
#  skip_cleanup: true
